# Generated by Django 4.1.10 on 2023-09-09 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.TextField()),
                ('issue', models.CharField(choices=[('', 'Select Issue'), ('nephrologist', 'Nephrologist Patient'), ('pediatrician', 'Pediatrician Patient'), ('eye', 'Eye Patient'), ('parental', 'Parental Patient'), ('liver', 'Liver Patient'), ('heart', 'Heart Patient')], max_length=30)),
                ('appointment_date', models.DateField()),
                ('doctor', models.ManyToManyField(to='authentications.userprofile')),
            ],
        ),
    ]
