# Generated by Django 4.1.10 on 2023-09-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientdetails',
            name='issue',
            field=models.CharField(choices=[('', 'Select Issue'), ('Nephrologist Patient', 'Nephrologist Patient'), ('Pediatrician Patient', 'Pediatrician Patient'), ('Eye Patient', 'Eye Patient'), ('Parental Patient', 'Parental Patient'), ('Liver Patient', 'Liver Patient'), ('Heart Patient', 'Heart Patient')], max_length=30),
        ),
    ]
