# Generated by Django 4.1.10 on 2023-09-09 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patientdetails_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='issue',
            field=models.CharField(choices=[('', 'Select Issue'), ('nephrologist', 'Nephrologist Patient'), ('pediatrician', 'Pediatrician Patient'), ('eye', 'Eye Patient'), ('parental', 'Parental Patient'), ('liver', 'Liver Patient'), ('heart', 'Heart Patient')], max_length=30),
        ),
    ]
