# Generated by Django 4.1.10 on 2023-09-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='doctor_name',
        ),
    ]
