# Generated by Django 4.1.10 on 2023-09-08 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
